version: "3.9"
services:
  webserver:
    build:
      context: ${PWD}/.docker
      args:
        PHP_VERSION: 8.2
    env_file:
      - .env
      - .docker/.env
    container_name: 'webserver-${CONTAINER_SUFFIX:-projections}'
    restart: 'unless-stopped'
    ports:
      - "${PORT_HTTP_EXTERNAL:-41}:${PORT_HTTP_INTERNAL:-80}"
    volumes:
      - ./:/var/www/html
      - ${PWD}/.docker/config/webserver/php.ini:/usr/local/etc/php/php.ini
      - ${PWD}/.docker/config/webserver/vhosts:/etc/apache2/sites-enabled
    environment:
      XDEBUG_CONFIG: "client_host=host.docker.internal"
      PHP_CS_FIXER_IGNORE_ENV: 1

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - .docker/db/data:/var/lib/postgresql/data:rw
