###
### 0. Create user
POST http://localhost:41/api/users
Content-Type: application/json

{
  "id": "{{$random.uuid}}",
  "name": "John Ford",
  "email": "{{$random.email}}",
  "profilePicture": "https://random"
}

